version: '2'
services:
  zookeeper:
    image: zookeeper
    restart: on-failure
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
  dubbo-admin:
    image: chenchuxin/dubbo-admin
    restart: on-failure
    container_name: dubbo-admin
    environment:
      - dubbo.registry.address=zookeeper://zookeeper:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest
    ports:
      - "8082:8080"